/* 
 * Contacts API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Swagger.Client.CSharp4.Client;
using Swagger.Client.CSharp4.Model;

namespace Swagger.Client.CSharp4.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDiceApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Swagger.Client.CSharp4.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sides"> (optional, default to 6)</param>
        /// <param name="amount"> (optional, default to 1)</param>
        /// <returns>DiceDto</returns>
        DiceDto ApiDiceGet (int? sides = null, int? amount = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Swagger.Client.CSharp4.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sides"> (optional, default to 6)</param>
        /// <param name="amount"> (optional, default to 1)</param>
        /// <returns>ApiResponse of DiceDto</returns>
        ApiResponse<DiceDto> ApiDiceGetWithHttpInfo (int? sides = null, int? amount = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Swagger.Client.CSharp4.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sides"> (optional, default to 6)</param>
        /// <param name="amount"> (optional, default to 1)</param>
        /// <returns>Task of DiceDto</returns>
        System.Threading.Tasks.Task<DiceDto> ApiDiceGetAsync (int? sides = null, int? amount = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Swagger.Client.CSharp4.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sides"> (optional, default to 6)</param>
        /// <param name="amount"> (optional, default to 1)</param>
        /// <returns>Task of ApiResponse (DiceDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<DiceDto>> ApiDiceGetAsyncWithHttpInfo (int? sides = null, int? amount = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DiceApi : IDiceApi
    {
        private CSharp4.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DiceApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DiceApi(String basePath)
        {
            this.Configuration = new CSharp4.Client.Configuration { BasePath = basePath };

            ExceptionFactory = CSharp4.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DiceApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DiceApi(CSharp4.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = CSharp4.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = CSharp4.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public CSharp4.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public CSharp4.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Swagger.Client.CSharp4.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sides"> (optional, default to 6)</param>
        /// <param name="amount"> (optional, default to 1)</param>
        /// <returns>DiceDto</returns>
        public DiceDto ApiDiceGet (int? sides = null, int? amount = null)
        {
             ApiResponse<DiceDto> localVarResponse = ApiDiceGetWithHttpInfo(sides, amount);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Swagger.Client.CSharp4.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sides"> (optional, default to 6)</param>
        /// <param name="amount"> (optional, default to 1)</param>
        /// <returns>ApiResponse of DiceDto</returns>
        public ApiResponse< DiceDto > ApiDiceGetWithHttpInfo (int? sides = null, int? amount = null)
        {

            var localVarPath = "/api/dice";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (sides != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "sides", sides)); // query parameter
            if (amount != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "amount", amount)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiDiceGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DiceDto>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DiceDto) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DiceDto)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Swagger.Client.CSharp4.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sides"> (optional, default to 6)</param>
        /// <param name="amount"> (optional, default to 1)</param>
        /// <returns>Task of DiceDto</returns>
        public async System.Threading.Tasks.Task<DiceDto> ApiDiceGetAsync (int? sides = null, int? amount = null)
        {
             ApiResponse<DiceDto> localVarResponse = await ApiDiceGetAsyncWithHttpInfo(sides, amount);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Swagger.Client.CSharp4.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sides"> (optional, default to 6)</param>
        /// <param name="amount"> (optional, default to 1)</param>
        /// <returns>Task of ApiResponse (DiceDto)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DiceDto>> ApiDiceGetAsyncWithHttpInfo (int? sides = null, int? amount = null)
        {

            var localVarPath = "/api/dice";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (sides != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "sides", sides)); // query parameter
            if (amount != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "amount", amount)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiDiceGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DiceDto>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DiceDto) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DiceDto)));
        }

    }
}
